apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/hyperkube:v${OPEROS_KUBERNETES_VERSION}
    imagePullPolicy: IfNotPresent
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --etcd-servers=http://localhost:2379
    - --allow-privileged=true
    - --service-cluster-ip-range=${OPEROS_SERVICE_CIDR}
    - --insecure-port=${OPEROS_KUBE_API_INSECURE_PORT}
    - --secure-port=${OPEROS_KUBE_API_SECURE_PORT}
    - --advertise-address=${OPEROS_CONTROLLER_IP}
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --runtime-config=extensions/v1beta1/networkpolicies=true
    - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: ${OPEROS_KUBE_API_INSECURE_PORT}
      hostPort: ${OPEROS_KUBE_API_INSECURE_PORT}
      name: https
    - containerPort: ${OPEROS_KUBE_API_SECURE_PORT}
      hostPort: ${OPEROS_KUBE_API_SECURE_PORT}
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host